port: 6727 # 监听端口
log_level: info # 日志等级
platform: 5 # 机器人客户端协议（1:Android 2:APad 3:Watch 4:IMac 5:IPad）
timeout: 30 #登录超时时间(秒)
group_whitelist: [] # 群消息白名单，为空表示全通过
general: # 通用配置，在单个配置省略时的默认值
  V11: # oneBotV11的通用配置
    heartbeat: 3 # 心跳间隔 (秒)
    access_token: '' # 访问api的token
    post_timeout: 15 # 上报超时时间，(秒)
    secret: '' # 上报数据的sha1签名密钥
    rate_limit_interval: 4 # ws心跳间隔(秒)
    post_message_format: string # "string"或"array"
    reconnect_interval: 3 # 重连间隔 (秒)
    use_http: true # 是否使用 http
    enable_cors: true # 是否允许跨域
    use_ws: true # 是否使用websocket
    http_reverse: [ ] # http上报地址
    ws_reverse: [ ] # 反向ws连接地址
  V12: # oneBotV12的通用配置
    heartbeat: 3 # 心跳间隔 (秒)
    access_token: '' # 访问api的token
    request_timeout: 15 # 上报超时时间 (秒)
    reconnect_interval: 3 # 重连间隔 (秒)
    enable_cors: true # 是否允许跨域
    use_http: true # 是否启用http
    use_ws: true # 是否启用 websocket
    webhook: [ ] # http 上报地址
    ws_reverse: [ ] # 反向ws连接地址
  protocol:
    platform: 2
# 每个账号的单独配置(用于覆盖通用配置)
123456789:
  version: V11 # 使用的oneBot版本
  protocol: # 将会覆盖通用配置中的protocol
    platform: 1
  # 。。。其他配置项参见上方对应oneBot版本的通用配置
